batch_size: 32
workers: 0
nepoch: 150
model_name: grnet
load_model: null
start_epoch: 0
num_points: 16384
work_dir: log/
flag: debug
loss: cd
manual_seed: null
use_mean_feature: False
step_interval_to_print: 500
epoch_interval_to_save: 1
epoch_interval_to_val: 1
varying_constant: null
varying_constant_epochs: null

lr: 1.e-4
lr_decay: True
lr_decay_interval: 50
lr_decay_rate: 0.5
lr_step_decay_epochs: null
lr_step_decay_rates: null
lr_clip: null
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

n_primitives: 16

# test
save_vis: True