batch_size: 32
workers: 8
nepoch: 200
model_name: gtnet
load_model: null
start_epoch: 0
num_points: 2048
work_dir: ./log_gtnet_2048/
flag: debug
loss: cd
manual_seed: 1
use_mean_feature: False
step_interval_to_print: 1
epoch_interval_to_save: 1
epoch_interval_to_val: 2
varying_constant: 1.0, 1.0, 1.0, 1.0
varying_constant_epochs: 15, 30, 50

lr: 0.0002
lr_decay: True
lr_decay_interval: 10
lr_decay_rate: 0.90
lr_step_decay_epochs: null
lr_step_decay_rates: null
lr_clip: 1.e-6
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

knn: 32
local_feature_dim: 128
global_feature_dim: 512
sample_ratio: 0.25
up_ratio: 4
# test
save_vis: False
